# Site settings
title: Othiel Glover
name: Othiel Glover

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/otglover
 - title: LinkedIn
   url: https://www.linkedin.com/otglover

#Any buzzword skills you want to include
skills:
 - GUI Models
 - Law Admin. Background
 - R Studio
 - SPSS
 - Microsoft Office
 - Excel Precision Tools
 - Tableau
 - SAS Enterprise Minor
 - Elite
 - SQL
 - Machine learning
 - Google Analytics
 - Project Management

#Work experience is required
roles:
 - title: GCFM - Lead Analyst
   start: 2015
   end: 2019
   employer: DLA Piper LLP - Global Client Financial Management
   description: Recruited to join an elite team of analyst that manage and develop top partner’s budgets for international clients and close any billing pitfalls to maximize profitability. Sleuthed out underlying rate problems that the firm’s partners were having and saved them on average 7% on lost revenue.
 - title: GCFM - Specialist
   start: 2013
   end: 2015
   employer: DLA Piper LLP - Global Client Financial Management
   description:	Guided the training of over 15 new interns and specialists on forecasting techniques and financial reporting procedures which gave them the skill set to be able to effectively manage over 250 global matters. 	Lead all new global matter workflows in Chicago which allowed me the freedom to create teams with other departments to close billing life cycle pitfalls in Chicago and lower billing turn around by 2 days.	Led the GCFM on a new leadership team called (C.U.T) created by top management to provide feedback on all new firm initiatives and unify departments to drive results. I lead the charge in training other department on cross function work, that lead to less turn over in other departments.
 - title: Project Controls 
   start: 2007
   end: 2011
   employer: Schiff Hardin LLP
   description: Consultant working closely with the Project Controls Practice Group. We did major project auditing and reforecasts for energy projects in North America.  
 - title: Project Assistant 
   start: 2005
   end: 2007
   employer: Schiff Hardin LLP
   description:	Major contributor to insurance trial preparation and conducted computerized searches to prepare for depositions, hearings and trials. Maintained the flow of legal documents both hard copy and electronic for over 500 cases, this led to consistent wins and steady revenue for the firm.
   
#Education is required
education:
 - level: Masters of Science 
   date: 2020
   subject: Business Analytics
   school: University of Notre Dame - Mendoza College of Business
 - level: Bachelor of Arts 
   date: 2005
   subject: Pre-Law with emphasis in Consumer Science
   school: University of Wisconsin - Madison
 
#List of interesting Github repo/projects to include - optional
github:
 - otglover/otglover.github.io

intro: |
  I am an Analytics Professional helping large-scale companies bring to light the hidden actionable insights in their data so senior leaders can drive out waste and unnecessary costs for improved margins and higher profit growth.
  I honed my skills at top global law firms and I'm looking for an opportunity to continue to grow my abilities in analytics modeling, data management and business intelligence. 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Business Intelligience</strong>: Successfully sold a new department to top business partners and the team I build in Chicago works on 90% of all global projects that originate in Chicago. <br/><br/>
   <strong>Microsoft Suite</strong>: Created a forecasting template via Excel precision tools that all analyst currently use when creating new forecasting and accrual reporting for new clients.  <br/><br/>
   <strong>Project Management</strong>: Successfully managed over 40 global projects over a 6-year period. <br/><br/>
   <strong>SQL&R</strong>: Built a regression model using R (Python) and SQL for a large government contractor (at Notre Dame) that allows them to predict if they will win a project. <br/><br/>
   <strong>C-Suite Dashboards</strong>: Prepared C-suite level dashboards via PowerPoint and Tableau for government contractor (at Notre Dame) that lead to our model being utilized by their contract managers via the provided GUI application.  <br/><br/>
   
